// ==UserScript==
// @name        VdexProject PC Sort Extension
// @namespace   http://userscripts.org/users/useridnumber
// @description Adds functionality to the PC. Including box swap, temp box, view all boxes, find, urls and notes.
// @include     http://vdexproject.net/pc.php?&mode=sort
// @version     1.12
// @grant   	none
// ==/UserScript==

var scriptCode = new Array();

// here's the build of the new script, one line at a time
scriptCode.push('// Initialises where the temp box sends pokemon when using shift+click');
scriptCode.push('var tempToBox = "pcbox1";');
scriptCode.push('// Used to find pokemon');
scriptCode.push('var pokedict = {};');
scriptCode.push('// Used to send only pokemon that have had their positions changed since the last save');
scriptCode.push('var initialpokedict = {};');
scriptCode.push('// Warn user if they can\'t use localstorage');
scriptCode.push('if (!isLocalStorageSupported) {');
scriptCode.push('    alert("Your browser is incompatible with saving notes");');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('// Remove the previous onclick behaviour of the pokemon and attach a custom function');
scriptCode.push('function redoLinks() {');
scriptCode.push('    var stockBtns = document.querySelectorAll("td.pcslot[onclick*=\'pcSelect\']");');
scriptCode.push('    for (var J = stockBtns.length - 1; J >= 0; --J) {');
scriptCode.push('        var oldClick = stockBtns[J].getAttribute("onclick");');
scriptCode.push('        var payloadMtch = oldClick.match(/(pcSelect.+?);/);');
scriptCode.push('        if (payloadMtch && payloadMtch.length > 1) {');
scriptCode.push('            var payload = payloadMtch[1];');
scriptCode.push('            //-- Dont use onclick!');
scriptCode.push('            stockBtns[J].removeAttribute("onclick");');
scriptCode.push('            //-- Store payload value.');
scriptCode.push('            stockBtns[J].setAttribute("data-destQry", payload);');
scriptCode.push('            //-- Activate click the proper way, especially for userscripts');
scriptCode.push('            stockBtns[J].addEventListener("click", function (event) {');
scriptCode.push('                enhansedSelect(this, event);');
scriptCode.push('            }, false);');
scriptCode.push('            var pokemonID = payload.split(", ")[1];');
scriptCode.push('            if (pokemondata[pokemonID]) {');
scriptCode.push('                pokemondata[pokemonID].push(stockBtns[J].id);');
scriptCode.push('                pokedict[pokemonID] = pokemondata[pokemonID];');
scriptCode.push('                initialpokedict[pokemonID] = stockBtns[J].id;');
scriptCode.push('            }');
scriptCode.push('        }');
scriptCode.push('    }');
scriptCode.push('}');
scriptCode.push('redoLinks();');
scriptCode.push('');
scriptCode.push('function redoPCInfo() {');
scriptCode.push('    var stockBtns = document.querySelectorAll("td.pcslot>img");');
scriptCode.push('    for (var J = stockBtns.length - 1; J >= 0; --J) {');
scriptCode.push('        var oldMouseOver = "" + stockBtns[J].onmouseover;');
scriptCode.push('        var imgsrc = "" + stockBtns[J].getAttribute("src");');
scriptCode.push('        var payloadMtch = oldMouseOver.match(/(pcInfo.+?);/);');
scriptCode.push('        if (payloadMtch && payloadMtch.length > 1) {');
scriptCode.push('            var payload = oldMouseOver.split("pcInfo(")[1];');
scriptCode.push('            payload = payload.split(")")[0];');
scriptCode.push('            stockBtns[J].removeAttribute("onmouseover");');
scriptCode.push('            //-- Store payload value.');
scriptCode.push('            stockBtns[J].setAttribute("pokeid", payload);');
scriptCode.push('            stockBtns[J].addEventListener("mouseover", function () {');
scriptCode.push('                pcInfo(this);');
scriptCode.push('            }, false);');
scriptCode.push('        }');
scriptCode.push('    }');
scriptCode.push('}');
scriptCode.push('redoPCInfo();');
scriptCode.push('');
scriptCode.push('function reformatPage() {');
scriptCode.push('    // Show all boxes');
scriptCode.push('    $(".pc").show();');
scriptCode.push('    // move all of the elements associated with the party into the pcparty div');
scriptCode.push('    var ldingbtn = $("<div></div>").attr("style", "height: 25px;");');
scriptCode.push('    ldingbtn.append($("#loading"));');
scriptCode.push('    var reloadpty = $(".content small")[0];');
scriptCode.push('	var pcpartyholder = $("<div></div>").attr({');
scriptCode.push('        id: "partydiv",');
scriptCode.push('        class: "dispinline"');
scriptCode.push('    });');
scriptCode.push('    pcpartyholder.append($("#pcparty"));');
scriptCode.push('    pcpartyholder.append(reloadpty);');
scriptCode.push('    pcpartyholder.append("<br><br><br>");');
scriptCode.push('    pcpartyholder.append(ldingbtn);');
scriptCode.push('    pcpartyholder.append("<br>");');
scriptCode.push('    pcpartyholder.append(\'<div style="height: 30px;"><div id="msg" style="display: none;"></div></div>\');');
scriptCode.push('    // create new div container for all static banner elements');
scriptCode.push('    var infofloatelm = $("<div></div>").attr({');
scriptCode.push('        id: "staticbanner",');
scriptCode.push('        class: "staticcontent"');
scriptCode.push('    });');
scriptCode.push('    $("#postpage").prepend(infofloatelm);');
scriptCode.push('    // create the temp box area');
scriptCode.push('    var tbldiv = $("<div></div>").attr({');
scriptCode.push('        id: "pctemp1",');
scriptCode.push('        class: "pc"');
scriptCode.push('    });');
scriptCode.push('    var tblelm = $("<table></table>").attr({');
scriptCode.push('        id: "pcboxtemp1",');
scriptCode.push('        class: "pcbox dispinline",');
scriptCode.push('        draggable: "true",');
scriptCode.push('        cellpadding: "0",');
scriptCode.push('        cellspacing: "1"');
scriptCode.push('    });');
scriptCode.push('    var tblbody = $("<tbody></tbody>");');
scriptCode.push('    tblbody.append("<tr><td class=\'boxtitle\' colspan=\'9\'><b>Temp</b></td></tr>");');
scriptCode.push('    var i, j;');
scriptCode.push('    var temprows = 5;');
scriptCode.push('    var tempcols = 9;');
scriptCode.push('    var maxslots = 42;');
scriptCode.push('    for (i = 0; i < temprows; i++) {');
scriptCode.push('        var tblrow = $("<tr></tr>");');
scriptCode.push('        for (j = 0; j < tempcols; j++) {');
scriptCode.push('            if ((i * tempcols + j) < maxslots) {');
scriptCode.push('                var tblcell = $("<td></td>").attr({');
scriptCode.push('                    id: "pcboxtemp1slot" + (i * tempcols + j + 1),');
scriptCode.push('                    class: "pcslot",');
scriptCode.push('                        \'data-destQry\': "pcSelect(this.id, 0, temp1, " + (i * tempcols + j + 1) + ");"');
scriptCode.push('                });');
scriptCode.push('                tblcell.mouseover(function () {');
scriptCode.push('                    if (this.className == "pcslot") {');
scriptCode.push('                        this.className = "pcslot-hover";');
scriptCode.push('                    }');
scriptCode.push('                });');
scriptCode.push('                tblcell.mouseout(function () {');
scriptCode.push('                    if (this.className == "pcslot-hover") {');
scriptCode.push('                        this.className = "pcslot";');
scriptCode.push('                    }');
scriptCode.push('                });');
scriptCode.push('                tblcell.click(function (event) {');
scriptCode.push('                    enhansedSelect(this, event);');
scriptCode.push('                });');
scriptCode.push('                var tblcellimg = $("<img>").attr({');
scriptCode.push('                    src: "./zangoose/32.gif",');
scriptCode.push('                    alt: ""');
scriptCode.push('                });');
scriptCode.push('                tblcell.append(tblcellimg);');
scriptCode.push('                tblrow.append(tblcell);');
scriptCode.push('            }');
scriptCode.push('        }');
scriptCode.push('        if (i == 4) {');
scriptCode.push('            var finalcell = $("<td>To: Box 1</td>").attr({');
scriptCode.push('                id: "transferBoxInfo",');
scriptCode.push('                class: "tempCell",');
scriptCode.push('                colspan: 3');
scriptCode.push('            });');
scriptCode.push('            tblrow.append(finalcell);');
scriptCode.push('        }');
scriptCode.push('        tblbody.append(tblrow);');
scriptCode.push('    }');
scriptCode.push('    tblelm.append(tblbody);');
scriptCode.push('    // create infodivtabs buttons');
scriptCode.push('    var infodivbtn = $("<span>Info</span>").attr({');
scriptCode.push('        id: "infodivbtn",');
scriptCode.push('        class: "btnclickable"');
scriptCode.push('    });');
scriptCode.push('    infodivbtn.click(function () {');
scriptCode.push('        $("#infodiv").show();');
scriptCode.push('        $("#urldiv").hide();');
scriptCode.push('        $("#notesdiv").hide();');
scriptCode.push('        $("#finddiv").hide();');
scriptCode.push('    });');
scriptCode.push('    var urldivbtn = $("<span>URLs</span>").attr({');
scriptCode.push('        id: "urldivbtn",');
scriptCode.push('        class: "btnclickable"');
scriptCode.push('    });');
scriptCode.push('    urldivbtn.click(function () {');
scriptCode.push('        $("#infodiv").hide();');
scriptCode.push('        $("#urldiv").show();');
scriptCode.push('        $("#notesdiv").hide();');
scriptCode.push('        $("#finddiv").hide();');
scriptCode.push('    });');
scriptCode.push('    var notesdivbtn = $("<span>Note</span>").attr({');
scriptCode.push('        id: "notesdivbtn",');
scriptCode.push('        class: "btnclickable"');
scriptCode.push('    });');
scriptCode.push('    notesdivbtn.click(function () {');
scriptCode.push('        $("#infodiv").hide();');
scriptCode.push('        $("#urldiv").hide();');
scriptCode.push('        $("#notesdiv").show();');
scriptCode.push('        $("#finddiv").hide();');
scriptCode.push('    });');
scriptCode.push('    var finddivbtn = $("<span>Find</span>").attr({');
scriptCode.push('        id: "finddivbtn",');
scriptCode.push('        class: "btnclickable"');
scriptCode.push('    });');
scriptCode.push('    finddivbtn.click(function () {');
scriptCode.push('        $("#infodiv").hide();');
scriptCode.push('        $("#urldiv").hide();');
scriptCode.push('        $("#notesdiv").hide();');
scriptCode.push('        $("#finddiv").show();');
scriptCode.push('    });');
scriptCode.push('    var btndiv = $("<div></div>").attr({');
scriptCode.push('        id: "btndiv",');
scriptCode.push('        class: "dispinline"');
scriptCode.push('    });');
scriptCode.push('    btndiv.append("( ");');
scriptCode.push('    btndiv.append(infodivbtn);');
scriptCode.push('    btndiv.append(" | ");');
scriptCode.push('    btndiv.append(urldivbtn);');
scriptCode.push('    btndiv.append(" | ");');
scriptCode.push('    btndiv.append(notesdivbtn);');
scriptCode.push('    btndiv.append(" | ");');
scriptCode.push('    btndiv.append(finddivbtn);');
scriptCode.push('    btndiv.append(" )");');
scriptCode.push('    // create other infodivtabs ie. urls, notes, find');
scriptCode.push('    var urldivtab = $("<div></div>").attr({');
scriptCode.push('        id: "urldiv",');
scriptCode.push('        class: "infodivtab"');
scriptCode.push('    });');
scriptCode.push('    urldivtab.append(\'<br><input id="pokePageBtn" type="button" class="btn" value="View page in new tab"><p class="title">Icon Img URL</p><input id="smallPokeURL" type="text" class="infoinput"><p class="title">Full Img URL</p><input id="bigPokeURL" type="text" class="infoinput">\');');
scriptCode.push('    var notesdivtab = $("<div></div>").attr({');
scriptCode.push('        id: "notesdiv",');
scriptCode.push('        class: "infodivtab"');
scriptCode.push('    });');
scriptCode.push('    notesdivtab.append(\'<div id="pokenote"></div><textarea id="notesarea" rows="20" cols="5" style="width: 260px; height: 90px;"></textarea><br><input id="saveNotes" pokeid="0" type="button" class="btn" value="Save Note">\');');
scriptCode.push('    var finddivtab = $("<div></div>").attr({');
scriptCode.push('        id: "finddiv",');
scriptCode.push('        class: "infodivtab"');
scriptCode.push('    });');
scriptCode.push('    finddivtab.append(\'<label>ID:</label><input id="findID" type="text" class="findinput"><br><label>Name:</label><input id="findName" type="text" class="findinput"><br><label>Nature:</label><input id="findNature" type="text" class="findinput"><br><input id="findPoke" type="button" class="btn" value="Find"><p id="findresult"></p><br><div id="unseldiv" hidden="true">[ <span id="unselectfind" class="hlclickable" >unselect</span> ]</div>\');');
scriptCode.push('    var infoparent = $("<div></div>").attr({');
scriptCode.push('        id: "infoparentdiv",');
scriptCode.push('        class: "dispinline"');
scriptCode.push('    });');
scriptCode.push('    infoparent.append(btndiv);');
scriptCode.push('    infoparent.append($("#infodiv"));');
scriptCode.push('    infoparent.append(urldivtab);');
scriptCode.push('    infoparent.append(notesdivtab);');
scriptCode.push('    infoparent.append(finddivtab);');
scriptCode.push('    // add the pcpartyholder and infodiv to static banner');
scriptCode.push('    infofloatelm.append(tblelm);');
scriptCode.push('    infofloatelm.append(pcpartyholder);');
scriptCode.push('    infofloatelm.append(infoparent);');
scriptCode.push('    // add the event to the temp pc box, would have added it early but wasn\'t sure if the');
scriptCode.push('    // dom had been created properly.');
scriptCode.push('    document.getElementById("pcboxtemp1").addEventListener("dragstart", function (event) {');
scriptCode.push('        drag(event);');
scriptCode.push('    }, false);');
scriptCode.push('    document.getElementById("pcboxtemp1").addEventListener("drop", function (event) {');
scriptCode.push('        drop(event);');
scriptCode.push('    }, false);');
scriptCode.push('    document.getElementById("pcboxtemp1").addEventListener("dragover", function (event) {');
scriptCode.push('        allowDrop(event);');
scriptCode.push('    }, false);');
scriptCode.push('    // hide the info panels that aren\'t needed currently');
scriptCode.push('    $("#urldiv").hide();');
scriptCode.push('    $("#notesdiv").hide();');
scriptCode.push('    $("#finddiv").hide();');
scriptCode.push('');
scriptCode.push('    // Move boxes from table to a div under the static banner');
scriptCode.push('    var boxesdiv = $("<div></div>").attr({');
scriptCode.push('        id: "pcboxesdiv",');
scriptCode.push('        class: "staticcontent"');
scriptCode.push('    });');
scriptCode.push('    for (i = 1; i <= maxboxes; i++) {');
scriptCode.push('        var selector = "#pc" + i;');
scriptCode.push('        $(selector).attr({');
scriptCode.push('            style: "display: inline-block;",');
scriptCode.push('            draggable: "true"');
scriptCode.push('        });');
scriptCode.push('        document.getElementById("pc" + i).addEventListener("dragstart", function (event) {');
scriptCode.push('            drag(event);');
scriptCode.push('        }, false);');
scriptCode.push('        document.getElementById("pc" + i).addEventListener("drop", function (event) {');
scriptCode.push('            drop(event);');
scriptCode.push('        }, false);');
scriptCode.push('        document.getElementById("pc" + i).addEventListener("dragover", function (event) {');
scriptCode.push('            allowDrop(event);');
scriptCode.push('        }, false);');
scriptCode.push('        boxesdiv.append($(selector));');
scriptCode.push('    }');
scriptCode.push('    $("#postpage").append(boxesdiv);');
scriptCode.push('    $("#postpage>table").remove();');
scriptCode.push('');
scriptCode.push('    // add functions to buttons');
scriptCode.push('    $("#saveNotes").click(function () {');
scriptCode.push('        saveNote($("#saveNotes").attr("pokeid"));');
scriptCode.push('    });');
scriptCode.push('    $("#findPoke").click(findpoke);');
scriptCode.push('    document.getElementById("unselectfind").addEventListener("click", unselectfoundpoke, false);');
scriptCode.push('');
scriptCode.push('    // Change the (?) below each box to (^) and change the functionality from help message');
scriptCode.push('    // to box selector. This selects which box shift+click in the temp box sends a pokemon');
scriptCode.push('    // to.');
scriptCode.push('    // It is not recommended to create functions within loops because the function retains');
scriptCode.push('    // a copy to the original i and not the value.');
scriptCode.push('    for (i = 1; i <= maxboxes; i++) {');
scriptCode.push('        (function (iCopy) {');
scriptCode.push('            var selector = "setbox" + i;');
scriptCode.push('            var editspan = document.getElementById(selector).nextSibling.nextSibling;');
scriptCode.push('            editspan.removeAttribute("onclick");');
scriptCode.push('            editspan.addEventListener("click", function () {');
scriptCode.push('                tempToBox = "pcbox" + iCopy;');
scriptCode.push('                document.getElementById("transferBoxInfo").innerHTML = "To: Box " + iCopy;');
scriptCode.push('            }, false);');
scriptCode.push('            editspan.innerHTML = "^";');
scriptCode.push('        }(i));');
scriptCode.push('    }');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('reformatPage();');
scriptCode.push('');
scriptCode.push('// changes static banner between fixed and absolute so that it scrolls with the page');
scriptCode.push('// when moving down through boxes, but otherwise doesn\'t cover Vdex menus.');
scriptCode.push('$(window).scroll(function () {');
scriptCode.push('    if ($(window).scrollTop() >= 205) {');
scriptCode.push('        $("#staticbanner").css({');
scriptCode.push('            position: "fixed",');
scriptCode.push('            left: "50%",');
scriptCode.push('            top: "0"');
scriptCode.push('        });');
scriptCode.push('    } else {');
scriptCode.push('        $("#staticbanner").css({');
scriptCode.push('            position: "absolute",');
scriptCode.push('            top: "205px"');
scriptCode.push('        });');
scriptCode.push('    }');
scriptCode.push('});');
scriptCode.push('');
scriptCode.push('// create custom function to catch shift+click events');
scriptCode.push('function enhansedSelect(e, event) {');
scriptCode.push('    var clickStr = e.getAttribute("data-destQry");');
scriptCode.push('    var splitString = clickStr.split(", ");');
scriptCode.push('    splitString[0] = e.id;');
scriptCode.push('    splitString[3] = splitString[3].substring(0, splitString[3].length - 1);');
scriptCode.push('');
scriptCode.push('    if (event.shiftKey) {');
scriptCode.push('        // if the box is highlighted, unhighlight it and reduce the pokemon held by 1');
scriptCode.push('        if (e.className == "pcslot-selected") {');
scriptCode.push('            e.className = "pcslot";');
scriptCode.push('            numsel--;');
scriptCode.push('        }');
scriptCode.push('        // What box is the poke coming from?');
scriptCode.push('        var boxid = splitString[0].split("slot")[0];');
scriptCode.push('        var nextslot;');
scriptCode.push('        if (boxid !== "pcboxtemp1") {');
scriptCode.push('            // Find the next empty slot in the temp box');
scriptCode.push('            nextslot = nextEmpty("pcboxtemp1");');
scriptCode.push('        } else {');
scriptCode.push('            nextslot = nextEmpty(tempToBox);');
scriptCode.push('        }');
scriptCode.push('');
scriptCode.push('        if (!!nextslot) {');
scriptCode.push('            var nextslotstr = nextslot.getAttribute("data-destqry");');
scriptCode.push('            var nextslotsplit = nextslotstr.split(", ");');
scriptCode.push('            nextslotsplit[0] = nextslot.id;');
scriptCode.push('            nextslotsplit[3] = nextslotsplit[3].substring(0, nextslotsplit[3].length - 1);');
scriptCode.push('            // pcSelect the current slot');
scriptCode.push('            pcSelect(splitString[0], splitString[1], splitString[2], splitString[3]);');
scriptCode.push('            // pcSelect the temp slot');
scriptCode.push('            pcSelect(nextslotsplit[0], nextslotsplit[1], nextslotsplit[2], nextslotsplit[3]);');
scriptCode.push('        }');
scriptCode.push('        //alert(JSON.stringify(storeArr, null, 4));');
scriptCode.push('');
scriptCode.push('    } else {');
scriptCode.push('        pcSelect(splitString[0], splitString[1], splitString[2], splitString[3]);');
scriptCode.push('    }');
scriptCode.push('    return false;');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function nextEmpty(selector) {');
scriptCode.push('    var tempslots = $("#" + selector + " .pcslot");');
scriptCode.push('    for (var i = 0; i < tempslots.length; i++) {');
scriptCode.push('        var pokedata = tempslots[i].getAttribute("data-destqry");');
scriptCode.push('');
scriptCode.push('        if (pokedata.split(", ")[1] === "0") {');
scriptCode.push('            return tempslots[i];');
scriptCode.push('        }');
scriptCode.push('    }');
scriptCode.push('    return null;');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('// Over write the pcinfo function for the pc');
scriptCode.push('function pcInfo(e) {');
scriptCode.push('    var pid = e.getAttribute("pokeid");');
scriptCode.push('    var smallurl = e.getAttribute("src");');
scriptCode.push('    if (midajax) {');
scriptCode.push('        return;');
scriptCode.push('    }');
scriptCode.push('    var infosdiv = document.getElementById("infodiv");');
scriptCode.push('    var pinfo = document.getElementById("pokeinfo" + pid);');
scriptCode.push('    if (!!pinfo) {');
scriptCode.push('        infosdiv.innerHTML = pinfo.innerHTML;');
scriptCode.push('        fillURLdiv(pid, smallurl, true);');
scriptCode.push('        fillNotesdiv(pid, smallurl);');
scriptCode.push('    } else if (pokemondata[pid]) {');
scriptCode.push('        infosdiv.innerHTML = create_poke_info(pid);');
scriptCode.push('        fillURLdiv(pid, smallurl, false);');
scriptCode.push('        fillNotesdiv(pid, smallurl);');
scriptCode.push('    }');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function create_poke_info(pnum) {');
scriptCode.push('    var pdata = pokemondata[pnum];');
scriptCode.push('');
scriptCode.push('    var divhtml = "";');
scriptCode.push('    if (pdata.length > 5) {');
scriptCode.push('        divhtml += \'<div class="infoleft"><span class="highlight">\' + pdata[1] + "</span> nature.<br>";');
scriptCode.push('        divhtml += pdata[2] + " on " + pdata[3] + ".<br><br>";');
scriptCode.push('        divhtml += \'<span class="tag">Owner:</span> <span class="\' + pdata[4] + \'"><a href="user.php?user=\' + pdata[5] + \'">\' + pdata[6] + "</a></span><br>";');
scriptCode.push('        divhtml += \'<span class="tag">ID No.:</span> \' + pdata[7] + "<br><b>";');
scriptCode.push('        if (pdata[9] > 0) {');
scriptCode.push('            divhtml += \'<span class="tag">OT:</span> <span class="\' + pdata[8] + \'"><a href="user.php?user=\' + pdata[9] + \'">\' + pdata[10] + "</a></span><br>";');
scriptCode.push('        } else {');
scriptCode.push('            divhtml += \'<span class="tag">OT:</span> ?????</span><br>\';');
scriptCode.push('        }');
scriptCode.push('        divhtml += \'<span class="tag">ID No.:</span> \' + pdata[11] + "<br><br>";');
scriptCode.push('        divhtml += "</div>";');
scriptCode.push('        divhtml += \'<div class="inforight"><span class="name">\' + pdata[12] + "</span>" + pdata[13] + "<br>";');
scriptCode.push('        divhtml += \'<span class="lv">Lv.</span>\' + pdata[14] + "<br>";');
scriptCode.push('        divhtml += \'<img src="http://zangoose.vdexproject.net/items/\' + pdata[15] + \'.png" alt="" title="" />\' + pdata[16] + "<br>";');
scriptCode.push('        divhtml += "<b>Item</b><br>";');
scriptCode.push('        divhtml += \'<span id="poke\' + pdata[0] + \'itm">\' + pdata[17] + "</span></div>";');
scriptCode.push('        divhtml += "</div>";');
scriptCode.push('    } else {');
scriptCode.push('        divhtml += \'<div class="infoleft">Received on \' + pdata[1] + ".<br><br>";');
scriptCode.push('        divhtml += "<b>Status</b><br>";');
scriptCode.push('        divhtml += pdata[2] + "<br><br></div>";');
scriptCode.push('        divhtml += \'<div class="inforight"><span class="name">Egg</span><br>\';');
scriptCode.push('        divhtml += pdata[3] + "<br>";');
scriptCode.push('        divhtml += "</div>";');
scriptCode.push('        divhtml += "</div>";');
scriptCode.push('    }');
scriptCode.push('    return (divhtml);');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function fillURLdiv(pnum, smallurl, refreshed) {');
scriptCode.push('    var pokeurl = "poke.php?id=" + pnum;');
scriptCode.push('    var pokeinfobtn = document.getElementById("pokePageBtn");');
scriptCode.push('    pokeinfobtn.onclick = function () {');
scriptCode.push('        window.open(pokeurl, "_blank");');
scriptCode.push('    };');
scriptCode.push('    var bigurl = "";');
scriptCode.push('    if (refreshed) {');
scriptCode.push('        if(smallurl.indexOf("icon/egg.png") == -1) {');
scriptCode.push('    	    var selector = "pokeimg" + pnum;');
scriptCode.push('    	    bigurl = document.getElementById(selector).getAttribute("src");');
scriptCode.push('        } else {');
scriptCode.push('    		bigurl = "http://zangoose.vdexproject.net/poke/egg.png";');
scriptCode.push('    	}');
scriptCode.push('    } else {');
scriptCode.push('	    var pdata = pokemondata[pnum];');
scriptCode.push('    	if (pdata.length > 5) {');
scriptCode.push('        	bigurl = pdata[16].split(\'src="\')[1];');
scriptCode.push('    	} else {');
scriptCode.push('        	bigurl = pdata[3].split(\'src="\')[1];');
scriptCode.push('    	}');
scriptCode.push('    	bigurl = bigurl.split(\'"\')[0];');
scriptCode.push('    }');
scriptCode.push('    var bigurltxt = "[url=http://vdexproject.net/poke.php?id=" + pnum + "][img]" + bigurl + "[/img][/url]";');
scriptCode.push('    var smallurltxt = "[url=http://vdexproject.net/poke.php?id=" + pnum + "][img]" + smallurl + "[/img][/url]";');
scriptCode.push('');
scriptCode.push('    document.getElementById("smallPokeURL").value = smallurltxt;');
scriptCode.push('    document.getElementById("bigPokeURL").value = bigurltxt;');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function fillNotesdiv(pnum, smallurl) {');
scriptCode.push('    if (localStorage.getItem(pnum) !== null) {');
scriptCode.push('        var stringrep = localStorage[pnum];');
scriptCode.push('        document.getElementById("notesarea").value = stringrep;');
scriptCode.push('    } else {');
scriptCode.push('        document.getElementById("notesarea").value = "";');
scriptCode.push('    }');
scriptCode.push('    document.getElementById("pokenote").innerHTML = "<img src=\'" + smallurl + "\'> " + pnum;');
scriptCode.push('    document.getElementById("saveNotes").setAttribute("pokeid", pnum);');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function saveNote(pokeid) {');
scriptCode.push('    try {');
scriptCode.push('        localStorage[pokeid] = document.getElementById("notesarea").value;');
scriptCode.push('        alert("Note saved :3");');
scriptCode.push('    } catch (e) {');
scriptCode.push('        if (e == QUOTA_EXCEEDED_ERR) {');
scriptCode.push('            alert("Quota exceeded!"); //data wasn\'t successfully saved due to quota exceed so throw an error');
scriptCode.push('        }');
scriptCode.push('    }');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('var foundSlots = [];');
scriptCode.push('');
scriptCode.push('function findpoke() {');
scriptCode.push('    var pokemonID = document.getElementById("findID").value.replace(/\s+/g, "");');
scriptCode.push('    var pokemonName = document.getElementById("findName").value.toLowerCase();');
scriptCode.push('    var pokemonNature = document.getElementById("findNature").value.replace(",", "&#44;").toLowerCase();');
scriptCode.push('');
scriptCode.push('    if (foundSlots.length > 0) {');
scriptCode.push('        unselectfoundpoke();');
scriptCode.push('    }');
scriptCode.push('    var foundID, foundName, foundNature;');
scriptCode.push('    for (var key in pokedict) {');
scriptCode.push('        if (pokemonID && pokedict[key][0] == pokemonID) {');
scriptCode.push('            foundSlots.push(pokedict[key][pokedict[key].length - 1]);');
scriptCode.push('        } else if (pokemonName && pokedict[key][12]) {');
scriptCode.push('            foundName = pokedict[key][12].toLowerCase();');
scriptCode.push('            if (pokemonName == foundName) {');
scriptCode.push('                foundSlots.push(pokedict[key][pokedict[key].length - 1]);');
scriptCode.push('            }');
scriptCode.push('        } else if (pokemonNature && pokedict[key][1]) {');
scriptCode.push('            foundNature = pokedict[key][1].toLowerCase();');
scriptCode.push('            if (pokemonNature == foundNature) {');
scriptCode.push('                foundSlots.push(pokedict[key][pokedict[key].length - 1]);');
scriptCode.push('            }');
scriptCode.push('        }');
scriptCode.push('    }');
scriptCode.push('');
scriptCode.push('    document.getElementById("findresult").innerHTML = foundSlots.length + " pokemon found.";');
scriptCode.push('    document.getElementById("unseldiv").hidden = false;');
scriptCode.push('');
scriptCode.push('    var i;');
scriptCode.push('    for (i = 0; i < foundSlots.length; i++) {');
scriptCode.push('        document.getElementById(foundSlots[i]).className = "pcslot-found";');
scriptCode.push('    }');
scriptCode.push('');
scriptCode.push('    if (foundSlots[0]) {');
scriptCode.push('        scrollToAnchor(foundSlots[0]);');
scriptCode.push('    }');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function unselectfoundpoke() {');
scriptCode.push('    var i;');
scriptCode.push('    for (i = 0; i < foundSlots.length; i++) {');
scriptCode.push('        document.getElementById(foundSlots[i]).className = "pcslot";');
scriptCode.push('    }');
scriptCode.push('    document.getElementById("findresult").innerHTML = "";');
scriptCode.push('    document.getElementById("unseldiv").hidden = true;');
scriptCode.push('');
scriptCode.push('    foundSlots = [];');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('// adds drag functions');
scriptCode.push('function allowDrop(ev) {');
scriptCode.push('    ev.preventDefault();');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function drag(ev) {');
scriptCode.push('    ev.dataTransfer.setData("Text", ev.target.id);');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function drop(ev) {');
scriptCode.push('    ev.preventDefault();');
scriptCode.push('    var data = ev.dataTransfer.getData("Text");');
scriptCode.push('    swapPCs(data, upTo(ev.target, "div").id, ev);');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function swapPCs(pc1, pc2, event) {');
scriptCode.push('    var pc1selector, pc2selector, i;');
scriptCode.push('    var pc1str = "box" + pc1.replace("pc", "") + "slot";');
scriptCode.push('    var pc2str = "box" + pc2.replace("pc", "") + "slot";');
scriptCode.push('    var maxslots = 42;');
scriptCode.push('    if (pc1 == "staticbanner" || pc1 == "pcboxtemp1") {');
scriptCode.push('        pc1str = "pcboxtemp1slot";');
scriptCode.push('    } else if (pc2 == "staticbanner" || pc2 == "pcboxtemp1") {');
scriptCode.push('        pc2str = "pcboxtemp1slot";');
scriptCode.push('    }');
scriptCode.push('    console.log(pc1 + " " + pc2 + " " + pc1str + " " + pc2str);');
scriptCode.push('');
scriptCode.push('    for (i = 1; i <= maxslots; i++) {');
scriptCode.push('        pc1selector = pc1str + i;');
scriptCode.push('        pc2selector = pc2str + i;');
scriptCode.push('');
scriptCode.push('        enhansedSelect(document.getElementById(pc1selector), event);');
scriptCode.push('        enhansedSelect(document.getElementById(pc2selector), event);');
scriptCode.push('    }');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('// Find first ancestor of el with tagName or undefined if not found');
scriptCode.push('function upTo(el, tagName) {');
scriptCode.push('    tagName = tagName.toLowerCase();');
scriptCode.push('');
scriptCode.push('    do {');
scriptCode.push('        el = el.parentNode;');
scriptCode.push('        if (el.tagName.toLowerCase() == tagName) {');
scriptCode.push('            return el;');
scriptCode.push('        }');
scriptCode.push('    } while (el.parentNode);');
scriptCode.push('');
scriptCode.push('    return null;');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('// Creates the animated slide to the anchor tags using JQuery animate()');
scriptCode.push('function scrollToAnchor(aid) {');
scriptCode.push('    var aTag = $("#" + aid);');
scriptCode.push('    $("html,body").animate({');
scriptCode.push('        scrollTop: aTag.offset().top - 250');
scriptCode.push('    }, "slow");');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('// Rewrite pcSelect behaviour');
scriptCode.push('var selectedPokemon = [];');
scriptCode.push('');
scriptCode.push('function pcSelect(what, poke, box, slot) {');
scriptCode.push('    if (midajax) {');
scriptCode.push('        return;');
scriptCode.push('    }');
scriptCode.push('    var itm = document.getElementById(what);');
scriptCode.push('    if (itm.className == "pcslot" || itm.className == "pcslot-hover" || itm.className == "pcslot-item" || itm.className == "pcslot-ihover" || itm.className == "pcslot-found") {');
scriptCode.push('        itm.className = "pcslot-selected";');
scriptCode.push('        selectedPokemon[numsel] = {');
scriptCode.push('            pokemonID: poke,');
scriptCode.push('            boxID: box,');
scriptCode.push('            slotID: slot,');
scriptCode.push('            htmlID: what,');
scriptCode.push('            innerhtml: itm.innerHTML');
scriptCode.push('        };');
scriptCode.push('        //alert(JSON.stringify(selectedPokemon[numsel], null, 4));');
scriptCode.push('        numsel++;');
scriptCode.push('');
scriptCode.push('        // if two are selected, then switch their properties around.');
scriptCode.push('        if (numsel == 2) {');
scriptCode.push('');
scriptCode.push('            var indexfound;');
scriptCode.push('            // if either is not an empty slot, we should record which position the poke is being switched to');
scriptCode.push('            // so that we can send only the pokemon that have changed positions to the server.');
scriptCode.push('            if (selectedPokemon[0].pokemonID > 0) {');
scriptCode.push('                indexfound = changedpokes.indexOf(selectedPokemon[0].pokemonID);');
scriptCode.push('                if (indexfound > -1) {');
scriptCode.push('                    changedpokes[indexfound] = selectedPokemon[0].pokemonID;');
scriptCode.push('                } else {');
scriptCode.push('                    indexfound = numchanged;');
scriptCode.push('                    changedpokes[numchanged] = selectedPokemon[0].pokemonID;');
scriptCode.push('                    numchanged++;');
scriptCode.push('                }');
scriptCode.push('                tobox[indexfound] = selectedPokemon[1].boxID;');
scriptCode.push('                toslot[indexfound] = selectedPokemon[1].slotID;');
scriptCode.push('                // also need to update the pokedict to reflect changed positions');
scriptCode.push('                // however if a new pokemon is being added to the page via a refresh');
scriptCode.push('                // there won\'t be a pokedict entry for it');
scriptCode.push('                if (!!pokedict[selectedPokemon[0].pokemonID]) {');
scriptCode.push('                    pokedict[selectedPokemon[0].pokemonID][pokedict[selectedPokemon[0].pokemonID].length - 1] = selectedPokemon[1].htmlID;');
scriptCode.push('                } else {');
scriptCode.push('                    pokedict[selectedPokemon[0].pokemonID] = [];');
scriptCode.push('                	 pokedict[selectedPokemon[0].pokemonID][0] = selectedPokemon[1].htmlID;');
scriptCode.push('                }');
scriptCode.push('            }');
scriptCode.push('            if (selectedPokemon[1].pokemonID > 0) {');
scriptCode.push('                indexfound = changedpokes.indexOf(selectedPokemon[1].pokemonID);');
scriptCode.push('                if (indexfound > -1) {');
scriptCode.push('                    changedpokes[indexfound] = selectedPokemon[1].pokemonID;');
scriptCode.push('                } else {');
scriptCode.push('                    indexfound = numchanged;');
scriptCode.push('                    changedpokes[numchanged] = selectedPokemon[1].pokemonID;');
scriptCode.push('                    numchanged++;');
scriptCode.push('                }');
scriptCode.push('                tobox[indexfound] = selectedPokemon[0].boxID;');
scriptCode.push('                toslot[indexfound] = selectedPokemon[0].slotID;');
scriptCode.push('                if (!!pokedict[selectedPokemon[0].pokemonID]) {');
scriptCode.push('                    pokedict[selectedPokemon[0].pokemonID][pokedict[selectedPokemon[0].pokemonID].length - 1] = selectedPokemon[1].htmlID;');
scriptCode.push('                } else {');
scriptCode.push('                    pokedict[selectedPokemon[0].pokemonID] = [];');
scriptCode.push('                	 pokedict[selectedPokemon[0].pokemonID][0] = selectedPokemon[1].htmlID;');
scriptCode.push('                }');
scriptCode.push('            }');
scriptCode.push('');
scriptCode.push('            // gets the pcslot element and replaces the title');
scriptCode.push('            var itm1, title1, itm2, title2;');
scriptCode.push('            itm1 = document.getElementById(selectedPokemon[0].htmlID);');
scriptCode.push('            title1 = itm1.title.replace(selectedPokemon[0].slotID, "");');
scriptCode.push('            itm1.innerHTML = selectedPokemon[1].innerhtml;');
scriptCode.push('            itm1.className = "pcslot";');
scriptCode.push('            itm1.setAttribute("data-destQry", "pcSelect(this.id, " + selectedPokemon[1].pokemonID + ", " + selectedPokemon[0].boxID + ", " + selectedPokemon[0].slotID + ")");');
scriptCode.push('');
scriptCode.push('            itm2 = document.getElementById(selectedPokemon[1].htmlID);');
scriptCode.push('            title2 = itm2.title.replace(selectedPokemon[1].slotID, "");');
scriptCode.push('');
scriptCode.push('            itm2.innerHTML = selectedPokemon[0].innerhtml;');
scriptCode.push('            itm2.className = "pcslot";');
scriptCode.push('            itm2.setAttribute("data-destQry", "pcSelect(this.id, " + selectedPokemon[0].pokemonID + ", " + selectedPokemon[1].boxID + ", " + selectedPokemon[1].slotID + ")");');
scriptCode.push('');
scriptCode.push('            itm1.title = selectedPokemon[0].slotID + title2;');
scriptCode.push('            itm1.setAttribute("alt", selectedPokemon[0].slotID + title2);');
scriptCode.push('            itm2.title = selectedPokemon[1].slotID + title1;');
scriptCode.push('            itm2.setAttribute("alt", selectedPokemon[1].slotID + title1);');
scriptCode.push('            numsel = 0;');
scriptCode.push('            pcsaved = true;');
scriptCode.push('');
scriptCode.push('            var itm1img = document.querySelectorAll("#" + selectedPokemon[0].htmlID + " img")[0];');
scriptCode.push('            itm1img.addEventListener("mouseover", function () {');
scriptCode.push('                pcInfo(this);');
scriptCode.push('            }, false);');
scriptCode.push('');
scriptCode.push('            var itm2img = document.querySelectorAll("#" + selectedPokemon[1].htmlID + " img")[0];');
scriptCode.push('            itm2img.addEventListener("mouseover", function () {');
scriptCode.push('                pcInfo(this);');
scriptCode.push('            }, false);');
scriptCode.push('        }');
scriptCode.push('    } else {');
scriptCode.push('        itm.className = "pcslot";');
scriptCode.push('        numsel--;');
scriptCode.push('    }');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('// overwrite to check for ');
scriptCode.push('// 1. if there are any pokemon in the temp box');
scriptCode.push('// 2. check to make sure only sending changed positions');
scriptCode.push('function pcSend(changedpokes, tobox, toslot) {');
scriptCode.push('');
scriptCode.push('    if (!boxEmpty("pcboxtemp1")) {');
scriptCode.push('        alert("You must move pokemon in the temp box to your PC boxes.");');
scriptCode.push('    } else {');
scriptCode.push('        if (changedpokes.length > 0) {');
scriptCode.push('            var params = "mode=pc";');
scriptCode.push('            for (var i = 0; i < changedpokes.length; i++) {');
scriptCode.push('                if (initialpokedict[changedpokes[i]] != ("box" + tobox[i] + "slot" + toslot[i])) {');
scriptCode.push('                    params = params + "&poke" + i + "=" + changedpokes[i] + "&box" + i + "=" + tobox[i] + "&slot" + i + "=" + toslot[i];');
scriptCode.push('                }');
scriptCode.push('            }');
scriptCode.push('            target = "ajax.php";');
scriptCode.push('            if (params != "mode=pc") {');
scriptCode.push('            	savePC(target, params);');
scriptCode.push('            } else {');
scriptCode.push('            	pcsaved = false;');
scriptCode.push('	         }');
scriptCode.push('        }');
scriptCode.push('    }');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function boxEmpty(selector) {');
scriptCode.push('    var tempslots = $("#" + selector + " .pcslot");');
scriptCode.push('    for (var i = 0; i < tempslots.length; i++) {');
scriptCode.push('        var pokedata = tempslots[i].getAttribute("data-destqry");');
scriptCode.push('        if (pokedata.split(", ")[1] != "0") {');
scriptCode.push('            return false;');
scriptCode.push('        }');
scriptCode.push('    }');
scriptCode.push('    return true;');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function savePC(target, params) {');
scriptCode.push('    if (midajax) {');
scriptCode.push('        return;');
scriptCode.push('    }');
scriptCode.push('    midajax = true;');
scriptCode.push('    var xmlhttp = createXmlhttp();');
scriptCode.push('    var loaddiv = document.getElementById("loading");');
scriptCode.push('    var msgdiv = document.getElementById("msg");');
scriptCode.push('');
scriptCode.push('    xmlhttp.onreadystatechange = function () {');
scriptCode.push('        if (xmlhttp.readyState == 1) {');
scriptCode.push('            loaddiv.innerHTML = \'<img src="http://zangoose.vdexproject.net/loading.gif" alt="Loading..." />\';');
scriptCode.push('            $("div#msg").fadeOut(200);');
scriptCode.push('        }');
scriptCode.push('        if (xmlhttp.readyState == 4) {');
scriptCode.push('            loaddiv.innerHTML = \'<input type="button" class="btn" onclick="pcSend ( changedpokes, tobox, toslot );" value="Save!" />\';');
scriptCode.push('            msgdiv.innerHTML = xmlhttp.responseText;');
scriptCode.push('            var aerr = document.getElementById("ajaxerror2");');
scriptCode.push('            if (aerr && !!aerr.innerHTML) {');
scriptCode.push('                alert(aerr.innerHTML);');
scriptCode.push('                aerr.innerHTML = "";');
scriptCode.push('            }');
scriptCode.push('            $("div#msg").fadeIn(300);');
scriptCode.push('            pcsaved = false;');
scriptCode.push('            midajax = false;');
scriptCode.push('            if (document.getElementById("msg").innerHTML == "PC updated.") {');
scriptCode.push('                updateinitialpokedict();');
scriptCode.push('            }');
scriptCode.push('        }');
scriptCode.push('    };');
scriptCode.push('    sendRequest(xmlhttp, target, params);');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function updateinitialpokedict() {');
scriptCode.push('    for (var i = 0; i < changedpokes.length; i++) {');
scriptCode.push('        initialpokedict[changedpokes[i]] = "box" + tobox[i] + "slot" + toslot[i];');
scriptCode.push('    }');
scriptCode.push('    changedpokes = [];');
scriptCode.push('    tobox = [];');
scriptCode.push('    toslot = [];');
scriptCode.push('    numchanged = 0;');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function refreshparty(mode) {');
scriptCode.push('    if (midajax) {');
scriptCode.push('        return;');
scriptCode.push('    }');
scriptCode.push('    if (pcsaved) {');
scriptCode.push('        alert("Please save your PC before refreshing your party.");');
scriptCode.push('        return;');
scriptCode.push('    }');
scriptCode.push('    midajax = true;');
scriptCode.push('    var xmlhttp = createXmlhttp();');
scriptCode.push('    var target = ("kadabra/files/ajax/pc.php");');
scriptCode.push('    var prefresh = document.getElementById("prefresh");');
scriptCode.push('    var ajaxdiv = document.getElementById("ajaxresponsediv");');
scriptCode.push('    prefresh.className = "";');
scriptCode.push('    prefresh.onclick = "";');
scriptCode.push('    prefresh.innerHTML = "refreshing...";');
scriptCode.push('    var params = "mode=partyrefresh";');
scriptCode.push('    if (mode) {');
scriptCode.push('        params += "&moder=" + mode;');
scriptCode.push('    }');
scriptCode.push('    xmlhttp.onreadystatechange = function () {');
scriptCode.push('        if (xmlhttp.readyState == 4) {');
scriptCode.push('            ajaxdiv.innerHTML = xmlhttp.responseText;');
scriptCode.push('            var aerr = document.getElementById("ajaxerror");');
scriptCode.push('            if (aerr) {');
scriptCode.push('                alert(aerr.innerHTML);');
scriptCode.push('            } else {');
scriptCode.push('                var aparty = document.getElementById("ajaxparty");');
scriptCode.push('                if (!aparty) {');
scriptCode.push('                    alert("An error occurred.");');
scriptCode.push('                } else {');
scriptCode.push('                    var pparty = document.getElementById("pcparty");');
scriptCode.push('                    pparty.innerHTML = aparty.innerHTML;');
scriptCode.push('                    redoLinks();');
scriptCode.push('                    redoPCInfo();');
scriptCode.push('                    fixrefreshedpokeinfo("pcparty");');
scriptCode.push('                }');
scriptCode.push('            }');
scriptCode.push('            prefresh.className = "hlclickable";');
scriptCode.push('            prefresh.onclick = function () {');
scriptCode.push('                refreshparty(mode);');
scriptCode.push('            }');
scriptCode.push('            prefresh.innerHTML = "refresh party";');
scriptCode.push('            ajaxdiv.innerHTML = "";');
scriptCode.push('            if (selid[0]) {');
scriptCode.push('                var selslot = document.getElementById(selid[0]);');
scriptCode.push('                selslot.className = "pcslot";');
scriptCode.push('                selid[0] = false;');
scriptCode.push('                numsel = 0;');
scriptCode.push('            }');
scriptCode.push('            midajax = false;');
scriptCode.push('        }');
scriptCode.push('    }');
scriptCode.push('    sendRequest(xmlhttp, target, params);');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function refreshbox(box, mode) {');
scriptCode.push('    if (midajax) {');
scriptCode.push('        return;');
scriptCode.push('    }');
scriptCode.push('    if (pcsaved) {');
scriptCode.push('        alert("Please save your PC before refreshing this box.");');
scriptCode.push('        return;');
scriptCode.push('    }');
scriptCode.push('    midajax = true;');
scriptCode.push('    var xmlhttp = createXmlhttp();');
scriptCode.push('    var target = ("kadabra/files/ajax/pc.php");');
scriptCode.push('    var prefresh = document.getElementById("brefresh" + box);');
scriptCode.push('    var ajaxdiv = document.getElementById("ajaxresponsediv");');
scriptCode.push('    prefresh.className = "";');
scriptCode.push('    prefresh.onclick = "";');
scriptCode.push('    prefresh.innerHTML = "refreshing...";');
scriptCode.push('    var params = "mode=boxrefresh&box=" + box;');
scriptCode.push('    if (mode) {');
scriptCode.push('        params += "&moder=" + mode;');
scriptCode.push('    }');
scriptCode.push('    xmlhttp.onreadystatechange = function () {');
scriptCode.push('        if (xmlhttp.readyState == 4) {');
scriptCode.push('            ajaxdiv.innerHTML = xmlhttp.responseText;');
scriptCode.push('            var aerr = document.getElementById("ajaxerror");');
scriptCode.push('            if (aerr) {');
scriptCode.push('                alert(aerr.innerHTML);');
scriptCode.push('            } else {');
scriptCode.push('                var abox = document.getElementById("ajaxbox");');
scriptCode.push('                if (!abox) {');
scriptCode.push('                    alert("An error occurred.");');
scriptCode.push('                } else {');
scriptCode.push('                    var pbox = document.getElementById("pc" + box);');
scriptCode.push('                    pbox.innerHTML = abox.innerHTML;');
scriptCode.push('                    redoLinks();');
scriptCode.push('                    redoPCInfo();');
scriptCode.push('                    fixrefreshedbox(box);');
scriptCode.push('                    fixrefreshedpokeinfo(box);');
scriptCode.push('                }');
scriptCode.push('            }');
scriptCode.push('            ajaxdiv.innerHTML = "";');
scriptCode.push('            if (selid[0]) {');
scriptCode.push('                var selslot = document.getElementById(selid[0]);');
scriptCode.push('                selslot.className = "pcslot";');
scriptCode.push('                selid[0] = false;');
scriptCode.push('                numsel = 0;');
scriptCode.push('            }');
scriptCode.push('            midajax = false;');
scriptCode.push('        }');
scriptCode.push('    }');
scriptCode.push('    sendRequest(xmlhttp, target, params);');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function fixrefreshedbox(box) {');
scriptCode.push('    var selector = "setbox" + box;');
scriptCode.push('    var editspan = document.getElementById(selector).nextSibling.nextSibling;');
scriptCode.push('    editspan.removeAttribute("onclick");');
scriptCode.push('    editspan.addEventListener("click", function () {');
scriptCode.push('        tempToBox = "pcbox" + box;');
scriptCode.push('        document.getElementById("transferBoxInfo").innerHTML = "To: Box " + box;');
scriptCode.push('    }, false);');
scriptCode.push('    editspan.innerHTML = "^";');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function fixrefreshedpokeinfo(box) {');
scriptCode.push('	var selector = "";');
scriptCode.push('	if (box != "pcparty") {');
scriptCode.push('		selector = "#pc" + box + " .hidden";');
scriptCode.push('	} else {');
scriptCode.push('		selector = "#" + box + " .hidden";');
scriptCode.push('	}');
scriptCode.push('');
scriptCode.push('	var newDivs = document.querySelectorAll(selector);');
scriptCode.push('    for (var i = 0; i < newDivs.length; i ++) {');
scriptCode.push('    	var element = newDivs[i];');
scriptCode.push('    	for (var j = 0; j < 4; j ++) {');
scriptCode.push('    		element.removeChild(element.firstChild);');
scriptCode.push('    	}');
scriptCode.push('    }');
scriptCode.push('}');
scriptCode.push('');
scriptCode.push('function isLocalStorageSupported() {');
scriptCode.push('    try {');
scriptCode.push('        var supported = false;');
scriptCode.push('        if (window["localStorage"] !== null) {');
scriptCode.push('            supported = true;');
scriptCode.push('        }');
scriptCode.push('        return supported;');
scriptCode.push('    } catch (e) {');
scriptCode.push('        return false;');
scriptCode.push('    }');
scriptCode.push('}');

// now, we put the script in a new script element in the DOM
var script = document.createElement('script');    // create the script element
script.innerHTML = scriptCode.join('\n');         // add the script code to it
scriptCode.length = 0;                            // recover the memory we used to build the script

document.getElementsByTagName('body')[0].appendChild(script);

function addGlobalStyle(css) {
    var head, style;
    head = document.getElementsByTagName('head')[0];
    if (!head) { return; }
    style = document.createElement('style');
    style.type = 'text/css';
    style.innerHTML = css;
    head.appendChild(style);
}

var cssscript = new Array();

cssscript.push('.dispinline {');
cssscript.push('    display: inline-block;');
cssscript.push('    vertical-align: top;');
cssscript.push('}');
cssscript.push('#infodiv {');
cssscript.push('    width: 280px;');
cssscript.push('    padding-left: 10px;');
cssscript.push('    padding-right: 10px;');
cssscript.push('    height: 180px;');
cssscript.push('}');
cssscript.push('.infoleft {');
cssscript.push('    width: 150px;');
cssscript.push('    padding-top: 5px;');
cssscript.push('    text-align: left;');
cssscript.push('    float: left;');
cssscript.push('}');
cssscript.push('.inforight {');
cssscript.push('    width: 130px;');
cssscript.push('    text-align: right;');
cssscript.push('    float: right;');
cssscript.push('}');
cssscript.push('.infodivtab {');
cssscript.push('    width: 280px;');
cssscript.push('    padding-left: 10px;');
cssscript.push('    padding-right: 10px;');
cssscript.push('    height: 180px;');
cssscript.push('}');
cssscript.push('#pcparty {');
cssscript.push('    text-align: center;');
cssscript.push('}');
cssscript.push('#pcboxtemp1 {');
cssscript.push('    padding-right: 10px;');
cssscript.push('}');
cssscript.push('#staticbanner {');
cssscript.push('    position:absolute;');
cssscript.push('    left:50%;');
cssscript.push('    margin-left:-475px;');
cssscript.push('    top:205px;');
cssscript.push('    z-index: 9999;');
cssscript.push('}');
cssscript.push('#pcboxesdiv {');
cssscript.push('    padding-top: 260px;');
cssscript.push('}');
cssscript.push('.staticcontent {');
cssscript.push('    text-align: center;');
cssscript.push('    background-color: #FFFFFF;');
cssscript.push('    width: 950px;');
cssscript.push('    margin: 0px auto;');
cssscript.push('    padding-top: 20px;');
cssscript.push('    padding-bottom: 20px;');
cssscript.push('}');
cssscript.push('.btnclickable {');
cssscript.push('    color: #e44848;');
cssscript.push('    cursor: pointer;');
cssscript.push('    font-size:x-small;');
cssscript.push('}');
cssscript.push('.absolutediv {');
cssscript.push('    margin: 0 auto;');
cssscript.push('}');
cssscript.push('.infoinput {');
cssscript.push('    font-size:x-small;');
cssscript.push('    height: 1em;');
cssscript.push('    width: 260px;');
cssscript.push('    margin-bottom: 5px;');
cssscript.push('}');
cssscript.push('.title {');
cssscript.push('    font-weight: bold;');
cssscript.push('    text-align: left;');
cssscript.push('}');
cssscript.push('#saveNotes {');
cssscript.push('    float: right;');
cssscript.push('}');
cssscript.push('textarea {');
cssscript.push('    margin-top: 10px;');
cssscript.push('    margin-bottom: 10px;');
cssscript.push('}');
cssscript.push('label {');
cssscript.push('    display: inline-block;');
cssscript.push('    width: 50px;');
cssscript.push('    text-align: right;');
cssscript.push('    margin-right: 10px;');
cssscript.push('    vertical-align: middle');
cssscript.push('}');
cssscript.push('.findinput {');
cssscript.push('    display: inline-block;');
cssscript.push('    margin-top: 10px;');
cssscript.push('    margin-bottom: 10px;');
cssscript.push('    width:200px');
cssscript.push('}');
cssscript.push('#findPoke {');
cssscript.push('    float: right;');
cssscript.push('    display:block;');
cssscript.push('}');
cssscript.push('.tempCell {');
cssscript.push('	border: 1px solid #eeeeee;');
cssscript.push('}');
cssscript.push('#findresult {');
cssscript.push('    text-align: center;');
cssscript.push('}');
cssscript.push('.pcslot-found {');
cssscript.push('			border: 1px solid #eeeeee;');
cssscript.push('			background-color: #00FF66;');
cssscript.push('			cursor: pointer;');
cssscript.push('}');
cssscript.push('#unseldiv {');
cssscript.push('	font-size:x-small;');
cssscript.push('}');

addGlobalStyle(cssscript.join('\n'));
